name: Tests

on:
  pull_request:
    branches:
      - main
      - 1.x
  push:
    branches:
      - main
      - 1.x

jobs:
  Test:
    strategy:
      matrix:
        ruby:
          - '3.0.3'
        rails:
          - '6.0'
          - '6.1'
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPORT: 5432
      POSTGRES_HOST: localhost
      POSTGRES_USERNAME: postgres
      POSTGRES_PORT: 5432
      COVERAGE: ${{ matrix.rails == '6.1' && matrix.ruby == '3.0.3' }}
      RAILS_VERSION: ${{matrix.rails}}
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}_ruby_${{ matrix.ruby }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
      AVO_LICENSE_KEY: license_123

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - id: build
      uses: ./.github/composite-build.yml
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Run tests
      id: run_tests
      run: bundle exec rspec

    - uses: actions/upload-artifact@v2
      if: always() && steps.run_tests.outcome == 'failure'
      with:
        name: rspec_failed_screenshots
        path: ./spec/dummy/tmp/screenshots

    - name: Generate coverage
      uses: codecov/codecov-action@v1
      if: ${{ env.COVERAGE }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage.xml
        name: codecov-umbrella

# bundle exec rspec ./spec/system/**/*.rb
